apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: veiculos
  template:
    metadata:
      labels:
        app: veiculos
    spec:
      containers:
        - name: veiculos
          image: lucaspcabral/veiculos:latest
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/veiculosdb?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: veiculos
spec:
  selector:
    app: veiculos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
